### ISSUE TITLE
Allow the Back/Erase key ⌫ to act as Delete

### ISSUE THREAD

**Issue by runxel** [nodepen/nodes#141]
Nearly all MacBooks in existence do not have a proper Delete key. You can do "fn + ⌫" to have a delete key, but that requires both hands, because them keys are so far away. Most apps on the Mac know this and don't force you to use that key combo.
So: Please let the back/erase key act as delete.

Thanks for your work, Chuck!

**Comment by cdriesler** [comment]
Will add this in for sure. If it's not obvious, I do all my desktop testing on a Windows machine. Currently looking into getting a macbook for proper testing.

Thanks for the report 👍
