### ISSUE TITLE
Generically handle gh param persistent data clearing

### ISSUE THREAD

**Issue by cdriesler** [nodepen/nodes#178]
Right now, the following code is repeated for every grasshopper parameter type when applying user-set values:

```
param.PersistentData.ClearValues();

// Do unique work

param.OnObjectChanged(GH_ObjectEventType.PersistentData);
```

Relevant code [here](https://github.com/nodepen/nodes/blob/abb5a4c360652e871a78099cf51ee7111b84f0e0/packages/converters/NodePenConvert.cs#L298).

I'd like to do this pre/post processing generically around the switch block. Because if I don't, then I _will_ forget to do this at some point and cause problems.

Right now, I use C# pattern matching to cast an `IGH_Param` to its specific param type (like `Param_Number`). The narrower type has the `PersistentData` property, but `IGH_Param` does not. So, code gets repeated in each block of the switch statement.

I've tried something like this:

```
var persistentParam = param as GH_PersistentParam<IGH_Goo>;

if (persistentParam != null) {
  // Do generic work
}
```

But `Param_Number` and `Param_Integer` (the only types being handled right now) both fail that cast. I'm assuming I'm misunderstanding something important here. But it feels like there should be a way to, given an `IGH_Param`:

- Detect if it has `PersistentData`
- Cast to the most generic type/interface with that property
- Perform pre/post processing on that reference
- Continue with the further param type narrowing in the switch block

**Comment by andrewheumann** [comment]
I thought for sure there was a way to do this, but we appear to be running into a fun little C# weirdness:
https://igoro.com/archive/fun-with-c-generics-down-casting-to-a-generic-type/

His solution 3 is no good for us since we don't control the types. 

In metahopper I used reflection to operate generically on `GH_PersistentParam<?>` objects:

```csharp
var method = param.GetType().GetMethods().Where(m => m.Name == "SetPersistentData").LastOrDefault();
if (method == null)
{
    AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "This param does not support persistent data");
    return;
}


var typeWeHave = dataToSet.First().GetType();
var list = Activator.CreateInstance(typeof(List<>).MakeGenericType(typeWeHave));
foreach(var item in dataToSet)
{
    list.GetType().GetMethod("Add").Invoke(list, new[] { item });
}

var setMethod = GetType().GetMethods(System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic).First(m => m.Name.Contains("SetData"));

OnPingDocument().ScheduleSolution(5, (doc) =>
 {
     setMethod.MakeGenericMethod(typeWeHave).Invoke(this, new[] { param, list });
 });
```
it's ugly, but it works!

**Comment by M-JULIANI** [comment]
@cdriesler have you checked whether this method clears `PersistentData`: https://developer.rhino3d.com/api/grasshopper/html/M_Grasshopper_Kernel_GH_Param_1_ClearData.htm ?

This inheritance tree suggests that might be the case (?) https://developer.rhino3d.com/api/grasshopper/html/T_Grasshopper_Kernel_GH_Param_1.htm

**Comment by M-JULIANI** [comment]
This solution uses reflection as well: https://discourse.mcneel.com/t/using-member-of-gh-persistentparam-t-without-knowing-t/44240/2

**Comment by cdriesler** [comment]
@M-JULIANI This is great stuff, thanks! Had no clue about the utility method, I think I'll reach for that.

I was using that other `ClearData` before on the same assumption. But it wasn't behaving like I expected. Probably some other stuff there I don't understand.
