### ISSUE TITLE
Improve build and test instructions

### ISSUE THREAD

**Issue by sbaer** [nodepen/nodes#52]
I went to https://github.com/cdriesler/nodepen/tree/main/app

and ran `yarn dev`

I get an error

$ next dev
/bin/sh: next: command not found

**Comment by cdriesler** [comment]
ty for taking a look, this is long overdue

More detailed instructions are now in the root Readme, lmk if you give it a try and run into issues. I don't have a mac to test on, if that's what you develop on.

**Comment by cdriesler** [comment]
18 months and a rewrite or two later, I've finally taken this part of being open source a little more seriously.

Instructions were just merged, let me know if you give it a try!
